name: GitHub - Activity

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Update repo's README with recent activity
    
    steps:
      - uses: actions/checkout@v2
      - uses: cocoataster/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
